/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tw.yukina.portalframework.api;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static String getVersion() {
        return "0.0.1";
    }
}
